spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: book-service
          uri: lb://BOOK-SERVICE
          predicates:
            - Path=/v1/book/**
        - id: library-service
          uri: lb://LIBRARY-SERVICE
          predicates:
            - Path=/v1/library/**
      discovery:
        locator:
          enabled: true
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
  security:
    enabled: false